[package]
name = "haze-probe"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
haze-store = { path = "../haze-store" }

tokio = { workspace = true }
async-trait = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
rand = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
sqlx = { workspace = true }
dashmap = { workspace = true }
futures = { workspace = true }

# Probes
surge-ping = { workspace = true }
hickory-resolver = { workspace = true }
reqwest = { workspace = true }
url = { workspace = true }
rustls = { workspace = true }
tokio-rustls = { workspace = true }
webpki-roots = { workspace = true }

socket2 = { version = "0.6.5", features = ["all"] }
