[package]
name = "haze-auth"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
haze-store = { path = "../haze-store" }

webauthn-rs = { workspace = true }
url = { workspace = true }
uuid = { workspace = true }
dashmap = { workspace = true }
serde_json = { workspace = true }
argon2 = { workspace = true }
password-hash = { workspace = true }
rand = { workspace = true }
sha2 = { workspace = true }
base64 = { workspace = true }
serde = { workspace = true }
sqlx = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
chrono = { workspace = true }
axum = { workspace = true }
http = { workspace = true }
async-trait = { workspace = true }
